[phases.setup]
aptPkgs = ["libgl1", "libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender1", "libxcb1", "libx11-6"]

[phases.install]
cmds = ["python -m pip install -r backend/requirements.txt", "python -m pip uninstall -y opencv-contrib-python opencv-python"]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:8080 app:app"
