[phases.setup]
aptPkgs = ["libgl1", "libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:8080 app:app"
